// <auto-generated />
using System;
using IlpRepoBackend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IlpRepoBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MaxMark")
                        .HasColumnType("integer")
                        .HasColumnName("max_mark");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_name");

                    b.Property<string>("BatchType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("batch_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("batches", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.BoPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuddyId")
                        .HasColumnType("integer")
                        .HasColumnName("buddy_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BuddyId");

                    b.HasIndex("TraineeId");

                    b.ToTable("bo_phases", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Buddy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DuId")
                        .HasColumnType("integer")
                        .HasColumnName("du_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DuId");

                    b.ToTable("buddies", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.DocumentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("request_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("document_requests", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.DocumentSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SubmissionLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("submission_link");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RequestId");

                    b.ToTable("document_submissions", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Du", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("dus", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentType")
                        .HasColumnType("text")
                        .HasColumnName("assessment_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId")
                        .IsUnique();

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.FeedbackHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Header")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("header");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("feedback_headers", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.FeedbackHeaderResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("FeedbackHeaderId")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_header_id");

                    b.Property<int?>("FeedbackId")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackHeaderId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("feedback_header_responses", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.MenterForAProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenterId")
                        .HasColumnType("integer")
                        .HasColumnName("mentor_id");

                    b.Property<string>("MentorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mentor_type");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("MenterId");

                    b.HasIndex("ProjectId");

                    b.ToTable("menter_for_project", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("MentorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mentor_type");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("mentors", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DocumentRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("document_request_id");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("NotificationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notification_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DocumentRequestId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Poc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("pocs", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.PocsForProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PocId")
                        .HasColumnType("integer")
                        .HasColumnName("poc_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("PocId");

                    b.HasIndex("ProjectId");

                    b.ToTable("pocs_for_project", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("project_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Technology")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("technology");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.ProjectLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LinkId")
                        .HasColumnType("integer")
                        .HasColumnName("link_id");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_links", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.ProjectTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.HasIndex("ProjectId", "TraineeId")
                        .IsUnique();

                    b.ToTable("project_team", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ObtainedMark")
                        .HasColumnType("integer")
                        .HasColumnName("obtained_mark");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("TraineeId");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AadhaarId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("aadhaar_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text")
                        .HasColumnName("blood_group");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactNo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("emergency_contact_no");

                    b.Property<string>("EmergencyContactRelationship")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("emergency_contact_relationship");

                    b.Property<string>("HealthCondition")
                        .HasColumnType("text")
                        .HasColumnName("health_condition");

                    b.Property<string>("PersonalInterest")
                        .HasColumnType("text")
                        .HasColumnName("personal_interest");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AadhaarId")
                        .IsUnique();

                    b.HasIndex("BatchId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("trainees", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TraineeActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.ToTable("trainee_activity", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TraineeDu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DuId")
                        .HasColumnType("integer")
                        .HasColumnName("du_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("integer")
                        .HasColumnName("trainee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ojtMenter")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ojtMenter");

                    b.HasKey("Id");

                    b.HasIndex("DuId");

                    b.HasIndex("TraineeId");

                    b.ToTable("trainee_du", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TrainingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("integer")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("training_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("training_schedule", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.BoPhase", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Buddy", "Buddy")
                        .WithMany("BoPhases")
                        .HasForeignKey("BuddyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithMany("BoPhases")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Buddy");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Buddy", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Du", "Du")
                        .WithMany("Buddies")
                        .HasForeignKey("DuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Du");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.DocumentRequest", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Documents", "Document")
                        .WithMany("DocumentRequests")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Project", "Project")
                        .WithMany("DocumentRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.DocumentSubmission", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Documents", "Document")
                        .WithMany("DocumentSubmissions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.DocumentRequest", "DocumentRequest")
                        .WithMany("DocumentSubmissions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("DocumentRequest");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithOne("Feedback")
                        .HasForeignKey("IlpRepoBackend.Domain.Entities.Feedback", "TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.FeedbackHeaderResponse", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.FeedbackHeader", "FeedbackHeader")
                        .WithMany("FeedbackHeaderResponses")
                        .HasForeignKey("FeedbackHeaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Feedback", "Feedback")
                        .WithMany("FeedbackHeaderResponses")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feedback");

                    b.Navigation("FeedbackHeader");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.MenterForAProject", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Mentor", "Mentor")
                        .WithMany("MenterForProjects")
                        .HasForeignKey("MenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlpRepoBackend.Domain.Entities.Project", "Project")
                        .WithMany("MentersForProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.DocumentRequest", "DocumentRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("DocumentRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DocumentRequest");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.PocsForProject", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Poc", "Poc")
                        .WithMany("PocsForProjects")
                        .HasForeignKey("PocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlpRepoBackend.Domain.Entities.Project", "Project")
                        .WithMany("PocsForProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poc");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.ProjectLink", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Link", "Link")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Project", "Project")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Link");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.ProjectTeam", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithMany("ProjectTeams")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Result", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Assessment", "Assessment")
                        .WithMany("Results")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithMany("Results")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assessment");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Trainee", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Batch", "Batch")
                        .WithMany("Trainees")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IlpRepoBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TraineeActivity", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithMany("TraineeActivities")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TraineeDu", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Du", "Du")
                        .WithMany("TraineeDus")
                        .HasForeignKey("DuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IlpRepoBackend.Domain.Entities.Trainee", "Trainee")
                        .WithMany("TraineeDus")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Du");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.TrainingSchedule", b =>
                {
                    b.HasOne("IlpRepoBackend.Domain.Entities.Batch", "Batch")
                        .WithMany("TrainingSchedules")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Batch", b =>
                {
                    b.Navigation("Trainees");

                    b.Navigation("TrainingSchedules");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Buddy", b =>
                {
                    b.Navigation("BoPhases");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.DocumentRequest", b =>
                {
                    b.Navigation("DocumentSubmissions");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Documents", b =>
                {
                    b.Navigation("DocumentRequests");

                    b.Navigation("DocumentSubmissions");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Du", b =>
                {
                    b.Navigation("Buddies");

                    b.Navigation("TraineeDus");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Feedback", b =>
                {
                    b.Navigation("FeedbackHeaderResponses");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.FeedbackHeader", b =>
                {
                    b.Navigation("FeedbackHeaderResponses");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Link", b =>
                {
                    b.Navigation("ProjectLinks");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Mentor", b =>
                {
                    b.Navigation("MenterForProjects");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Poc", b =>
                {
                    b.Navigation("PocsForProjects");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Project", b =>
                {
                    b.Navigation("DocumentRequests");

                    b.Navigation("MentersForProjects");

                    b.Navigation("PocsForProjects");

                    b.Navigation("ProjectLinks");

                    b.Navigation("ProjectTeams");
                });

            modelBuilder.Entity("IlpRepoBackend.Domain.Entities.Trainee", b =>
                {
                    b.Navigation("BoPhases");

                    b.Navigation("Feedback");

                    b.Navigation("ProjectTeams");

                    b.Navigation("Results");

                    b.Navigation("TraineeActivities");

                    b.Navigation("TraineeDus");
                });
#pragma warning restore 612, 618
        }
    }
}
